
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftLABEL_INFUCI FUNC HALT JMP LABEL_IN LABEL_OUT LDI LOAD MOV OUT RESISTER STA VALUEcmd : MOV RESISTER RESISTERcmd : FUNC VALUE RESISTERcmd : LDI RESISTER VALUEcmd : FUCI VALUE VALUEcmd : LOAD RESISTER VALUEcmd : STA RESISTER VALUEcmd : FUNC VALUE VALUEcmd : JMP VALUE LABEL_OUTcmd : HALTcmd : OUT RESISTER VALUEcmd : LABEL_IN cmd'
    
_lr_action_items = {'MOV':([0,11,],[2,2,]),'FUNC':([0,11,],[3,3,]),'LDI':([0,11,],[4,4,]),'FUCI':([0,11,],[5,5,]),'LOAD':([0,11,],[6,6,]),'STA':([0,11,],[7,7,]),'JMP':([0,11,],[8,8,]),'HALT':([0,11,],[9,9,]),'OUT':([0,11,],[10,10,]),'LABEL_IN':([0,11,],[11,11,]),'$end':([1,9,20,21,22,23,24,25,26,27,28,29,],[0,-9,-11,-1,-7,-2,-3,-4,-5,-6,-8,-10,]),'RESISTER':([2,4,6,7,10,12,13,],[12,14,16,17,19,21,23,]),'VALUE':([3,5,8,13,14,15,16,17,19,],[13,15,18,22,24,25,26,27,29,]),'LABEL_OUT':([18,],[28,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cmd':([0,11,],[1,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cmd","S'",1,None,None,None),
  ('cmd -> MOV RESISTER RESISTER','cmd',3,'p_mov','excert.py',136),
  ('cmd -> FUNC VALUE RESISTER','cmd',3,'p_func_r','excert.py',150),
  ('cmd -> LDI RESISTER VALUE','cmd',3,'p_ldi','excert.py',160),
  ('cmd -> FUCI VALUE VALUE','cmd',3,'p_fuci','excert.py',179),
  ('cmd -> LOAD RESISTER VALUE','cmd',3,'p_load','excert.py',187),
  ('cmd -> STA RESISTER VALUE','cmd',3,'p_sta','excert.py',203),
  ('cmd -> FUNC VALUE VALUE','cmd',3,'p_func','excert.py',221),
  ('cmd -> JMP VALUE LABEL_OUT','cmd',3,'p_jmp','excert.py',230),
  ('cmd -> HALT','cmd',1,'p_halt','excert.py',240),
  ('cmd -> OUT RESISTER VALUE','cmd',3,'p_out','excert.py',245),
  ('cmd -> LABEL_IN cmd','cmd',2,'p_label','excert.py',259),
]
